name: CD - Build Docker Image

on:
  push:
    branches:
      - 'master'

concurrency:
  group: docker-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write

jobs:
  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Check repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set GHCR repo
        run: |
          GHCR_REPO=$(echo "${GITHUB_REPOSITORY@L}")
          echo "GHCR_REPO=$GHCR_REPO" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: ghcr.io/${{ env.GHCR_REPO }}:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ env.GHCR_REPO }}:buildcache,mode=max
          tags: |
            ghcr.io/${{ env.GHCR_REPO }}:v0.15.1-nix-9
